version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  spark:
    build: .
    environment:
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./data:/data
    env_file:
      - ".env"